apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: cf-k8s-api
  name: cf-k8s-api
  namespace: default
spec:
  virtualhost:
    fqdn: localhost
  routes:
  - conditions:
    - prefix: /
    services:
    - name: cf-k8s-api-svc
      port: 80
