apiVersion: v1
kind: Service
metadata:
  name: korifi-statefulset-runner-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: korifi-statefulset-runner

{{- if .Values.global.debug }}
---
apiVersion: v1
kind: Service
metadata:
  name: korifi-statefulset-runner-controller-manager-debug-port
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: debug-30054
      nodePort: 30054
      port: 30054
      protocol: TCP
      targetPort: 40000
  selector:
    app: korifi-statefulset-runner
  type: NodePort
{{- end }}
