apiVersion: v1
kind: ServiceAccount
metadata:
  name: korifi-job-task-runner-controller-manager
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: korifi-job-task-runner-leader-election-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: korifi-job-task-runner-leader-election-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: korifi-job-task-runner-leader-election-role
subjects:
- kind: ServiceAccount
  name: korifi-job-task-runner-controller-manager
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: korifi-job-task-runner-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: korifi-job-task-runner-taskworkload-manager-role
subjects:
- kind: ServiceAccount
  name: korifi-job-task-runner-controller-manager
  namespace: {{ .Values.namespace }}
