# permissions for end users to view cfserviceinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfserviceinstance-viewer-role
rules:
- apiGroups:
  - services.cloudfoundry.org
  resources:
  - cfserviceinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - services.cloudfoundry.org
  resources:
  - cfserviceinstances/status
  verbs:
  - get
