# permissions for end users to view cfservicebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfservicebinding-viewer-role
rules:
- apiGroups:
  - services.cloudfoundry.org
  resources:
  - cfservicebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - services.cloudfoundry.org
  resources:
  - cfservicebindings/status
  verbs:
  - get
