# permissions for end users to edit cfservicebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cfservicebinding-editor-role
rules:
- apiGroups:
  - services.cloudfoundry.org
  resources:
  - cfservicebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.cloudfoundry.org
  resources:
  - cfservicebindings/status
  verbs:
  - get
