kpackImageTag: localregistry-docker-registry.default.svc.cluster.local:30050/cf-k8s-controllers/kpack/images

clusterBuilderName: cf-kpack-cluster-builder
cfProcessDefaults:
  memoryMB: 500
  diskQuotaMB: 512
cfk8s_controller_namespace: cf-k8s-controllers-system
workloads_tls_secret_name: ""
