externalFQDN: "api.example.org"
internalPort: 9000
idleTimeout: 900
readTimeout: 900
readHeaderTimeout: 10
writeTimeout: 900

rootNamespace: cf
buildReconciler: kpack-image-builder
defaultLifecycleConfig:
  type: buildpack
  stack: cflinuxfs3
  stagingMemoryMB: 1024
  stagingDiskMB: 1024
packageRegistryBase: gcr.io/cf-relint-greengrass/korifi-controllers/kpack/beta
packageRegistrySecretName: image-registry-credentials # Create this secret in the rootNamespace
defaultDomainName: apps.example.org
