apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}-gateway
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: korifi
  namespace: {{ .Release.Namespace }}-gateway
spec:
  gatewayClassName: {{ .Values.networking.gatewayClass }}
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http-apps
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    hostname: {{ .Values.api.apiServer.url }}
    name: https-api
    port: 443
    protocol: TLS
    tls:
      mode: Passthrough
---
kind: TLSRoute
apiVersion: gateway.networking.k8s.io/v1alpha2
metadata:
  name: korifi-api
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: korifi
    namespace: {{ .Release.Namespace }}-gateway
  hostnames:
  - {{ .Values.api.apiServer.url }}
  rules:
  - backendRefs:
    - kind: Service
      name: korifi-api-svc
      port: 443
