apiVersion: apps/v1
kind: Deployment
metadata:
  name: hnc-controller-manager
  namespace: hnc-system
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
          # adding this to only check namespaces beginning with 'cf'
        - --included-namespace-regex=cf.*
          # changing this from 50
        - --apiserver-qps-throttle=50
          # the rest are from the default, but must be included :(
        - --webhook-server-port=9443
        - --metrics-addr=:8080
        - --max-reconciles=10
        - --excluded-namespace=kube-system
        - --excluded-namespace=kube-public
        - --excluded-namespace=hnc-system
        - --excluded-namespace=kube-node-lease
        - --enable-internal-cert-management
        - --cert-restart-on-secret-refresh
        resources:
          limits:
            # increase limit from 100m
            cpu: 500m
          requests:
            # increase request from 100m
            cpu: 200m
