cfRootNamespace: cf
clusterBuilderName: cf-kpack-cluster-builder
kpackImageTag: gcr.io/cf-relint-greengrass/korifi-controllers/kpack/beta
packageRegistrySecretName: image-registry-credentials # Create this secret in the rootNamespace
