apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: config
    behavior: merge
    files:
      - controllersconfig/kpack_build_controllers_config.yaml


resources:
  - ../../default
