---
apiVersion: v1
kind: Namespace
metadata:
  name: system
  labels:
    control-plane: controller-manager
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
