---
apiVersion: v1
kind: Service
metadata:
  name: korifi-kpack-image-builder-controller-manager-debug-port
  namespace: korifi-kpack-build-system
spec:
  ports:
  - name: debug-30053
    nodePort: 30053
    port: 30053
    protocol: TCP
    targetPort: 40000
  selector:
    app: korifi-kpack-image-builder-controller-manager
  type: NodePort
