# permissions for end users to edit appworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appworkload-editor-role
rules:
- apiGroups:
  - ext.cloudfoundry.org
  resources:
  - appworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ext.cloudfoundry.org
  resources:
  - appworkloads/status
  verbs:
  - get
