# permissions for end users to view appworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appworkload-viewer-role
rules:
- apiGroups:
  - ext.cloudfoundry.org
  resources:
  - appworkloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ext.cloudfoundry.org
  resources:
  - appworkloads/status
  verbs:
  - get
