name: Build and Push API Image after PR Test

on:
  workflow_run:
    workflows:
    - "Run API Tests on PR"
    branches:
    - main
    types:
    - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    needs: tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: relintdockerhubpushbot/cf-k8s-api:${{ env.GITHUB_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
