name: Build and Push Controllers Image after PR Test

on:
  workflow_run:
    workflows:
    - "Run Controllers Tests on PR"
    branches:
    - main
    types:
    - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    needs: tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./controllers
          push: true
          tags: relintdockerhubpushbot/cf-k8s-controllers:pr-${{ env.GITHUB_SHA }}
