name: Test, Build, and Push API Image from main

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**/*.md'
    - '.*/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: cf-k8s-controllers
    - uses: actions/checkout@v2
      with:
        repository: cloudfoundry-incubator/eirini-controller
        path: eirini-controller

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('cf-k8s-controllers/**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.0'

    - name: Runs API tests
      run: make test
      working-directory: ./cf-k8s-controllers/api

  build:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push API image
      uses: docker/build-push-action@v2
      with:
        context: ./api
        push: true
        tags: cloudfoundry/cf-k8s-api:latest
