name: Run API Tests on PR

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - '**/*.md'
    - '.*/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-reference:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17' # The Go version to download (if necessary) and use.

    - name: Check for reference YAML drift
      run: |
        make build-reference
        git diff --exit-code
      working-directory: ./api

  tests:
    needs: check-reference

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: cf-k8s-controllers
    - uses: actions/checkout@v2
      with:
        repository: cloudfoundry-incubator/eirini-controller
        path: eirini-controller

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('cf-k8s-controllers/**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - name: Run API tests
      run: make test
      working-directory: ./cf-k8s-controllers/api
