name: Run Tests on PR

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**/*.md'
    - '.*'

jobs:
  run-envtest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.x'

      - name: Run envtest
        run: make test

