name: Test, Build, and Push Controllers Image from main

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**/*.md'
    - '.*/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('cf-k8s-controllers/**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.x'

    - name: Run Controllers tests
      run: make test
      working-directory: ./controllers

  build:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push controllers image
      uses: docker/build-push-action@v2
      with:
        context: ./controllers
        push: true
        tags: cloudfoundry/cf-k8s-controllers:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
